### PR TITLE
Moved from JSDoc to type declarations for options objects

### LINKED ISSUE #49: Fix type declarations for options objects in uxp.d.ts
While TypeScript theoretically supports [declaring one-off types with the JSDoc format](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#typedef-callback-and-param), it doesn't work terribly well for ambient type declarations (`*.d.ts`). It appears to mainly provide context for type checking the usage of that type in the body of a function's definition.

Let's look at an example with the [`Entry.copyTo`](https://github.com/AdobeXD/typings/blob/357af6b3189f31b86c4393a920bd1262c4a48ea6/types/uxp.d.ts#L53) function. Here is how it's currently defined:

```ts
/**
 * Copies this entry to the specified `folder`.
 * @param folder the folder to which to copy this entry
 * @param {object} options additional options
 * @param {boolean=false} options.overwrite if `true`, allows overwriting existing entries
 *
 * @throws errors.EntryExistsError if the attempt would overwrite an entry and `overwrite` is `false`
 * @throws errors.PermissionDeniedError if the underlying file system rejects the attempt
 * @throws errors.OutOfSpaceError if the file system is out of storage space
 */
copyTo(folder: Folder, options?): Promise<void>;
```

As written, the TypeScript language service is already confused about the use of the `@param` directive. See:

image

Whoops! It didn't identify the `options.overwrite` parameter correctly. To do this in a way that satisfies TypeScript, we would write the following:

```ts
/**
 * @param {boolean} [options.overwrite=false] if `true`, allows overwriting existing entries
 */
```

Oddly, once you write it "correctly" for TypeScript, the `option` object's parameters disappear from the IntelliSense entirely:

image

Unfortunately, constructing the parameters in this way **_also_** doesn't help the language service with type checking. If you look at the type of the `options` parameter in that declaration it is considered `any`.

Oh no!

A much better and safer way to handle this is to implement the options parameters inline inside the declaration. Here's an example that uses the `copyTo` function:

```ts
/**
 * Copies this entry to the specified `folder`.
 * 
 * The Entry object passed to this function will continue to reference the original item - it is _not_ updated to reference the copy.
 * 
 * @param folder the folder to which to copy this entry
 * @param options
 *
 * @throws errors.EntryExistsError if the attempt would overwrite an entry and `overwrite` is `false`
 * @throws errors.PermissionDeniedError if the underlying file system rejects the attempt
 * @throws errors.OutOfSpaceError if the file system is out of storage space
 */
copyTo(folder: Folder, options?: {
    /**
     * if `true`, allows overwriting existing entries
     */
    overwrite?: boolean = false;
}): Promise<void>;
```

_[**Note:** The above version includes an updated body based on the [current docs](https://adobexdplatform.com/plugin-docs/reference/uxp/module/storage.html#module-storage-entry-copyto).]_

With this approach we get the following three benefits:

1. IntelliSense for options fields:
    image
1. Auto-completion when authoring:
    image
1. Error reporting when an incorrect type is used:
    image

## Another Option...

If inline parameter documentation is unappealing, there is one other method that could be used. It's more flexible, but less "precise" when it comes to Adobe's documentation. Specifically, you could define your own interface:

```ts
interface CopyToOptions {
     /**
     * if `true`, allows overwriting existing entries
     */
    overwrite?: boolean = false;
}
```

With the above, you would change the declaration of `copyTo` to the following:

```ts
copyTo(folder: Folder, options?: CopyToOptions): Promise<void>;
```

This provides the same exact benefits as the inline approach with _one **additional** benefit_: you can reuse that type!

```ts
/** @type {import("uxp").storage.CopyToOptions} */
let copyOptions = {
    overwrite: true
};
anEntry.copyTo(null, copyOptions);
```

That said, it is unlikely that many people would use such a feature...

### LINKED ISSUE #52: SceneNodeList "type" should move to scenegraph.d.ts
The [`SceneNodeList`](https://adobexdplatform.com/plugin-docs/reference/SceneNodeList.html) class should not be in the global context. Actual attempts to access the `SceneNodeList` directly in a command script results in `undefined` (it's not actually a global).

Further, this should probably be an **interface** rather than a class as there does not appear to be a way to create new instances yourself.

Therefore I would recommend moving the `SceneNodeList` declaration into `scenegraph.d.ts`, (the only location the type is actually referenced) and simultaneously convert it to an interface.

### LINKED ISSUE #53: Declaration Errors in assets.d.ts
If you convert the `jsconfig.json` file to a `tsconfig.json` file, set `strict: true`, and then open the `assets.d.ts` file (in VSCode, at least), you are presented with the following errors:

- A 'declare' modifier cannot be used in an already ambient context. `ts(1038) [119, 5]`
- A 'declare' modifier cannot be used in an already ambient context. `ts(1038) [155, 5]`

These refer to the fact that the `colors` and `characterStyles` classes are declared inside an already declared module.

Removing those `declare` statements results in further errors related to the definition of the `static class`. As both the `colors` and `characterStyles` "classes" are actually interfaces that allow you to _access_ information (you never have an "instance" of those "classes"), they should simply be converted to `interface`s and the `static` keyword removed from all function definitions. Then a constant should be added that implements that interface so that it is accessible as a name and not just a type. Taken together, the two "class"es should look something like this:

```ts
interface colors {
    get(): Array<ColorAsset | GradientAsset>;
    add(...): number;
    delete(...): number;
}

const colors: colors;
```

### LINKED ISSUE #55: Declarations Errors in cloud.d.ts
If you convert the `jsconfig.json` file to a `tsconfig.json` file, set `strict: true`, and then open the `assets.d.ts` file (in VSCode, at least), you are presented with the following errors:

- Enum type 'ArtifactType' has members with initializers that are not literals. `ts(2535) [9, 15]`
- Enum type 'ArtifactType' has members with initializers that are not literals. `ts(2535) [52, 15]`

These refer to the fact that you have the following in a `type` declaration:

```ts
type PrototypeArtifact = {
    type: ArtifactType.PROTOTYPE,  // <-- Can't do this with ambient enums!
```

The problem here is that you are assigning a _value_ to the type `PrototypeArtifact.type` but that you have not explicitly said what `ArtifactType.PROTOTYPE` is actually equivalent to. When you _declare_ an [ambient enum](https://www.typescriptlang.org/docs/handbook/enums.html#ambient-enums), you provide information on the names of each valid type but not the _value_. While this works for _usage_ of that enum entry, you cannot use it in another ambient type declaration as you do above.

That said, enums in JavaScript are simple objects and we can easily see what their values are with a quick test (though it would be nice if Adobe simply [_documented_](https://adobexdplatform.com/plugin-docs/reference/cloud.html#enums) them...):

```js
// Outputs:
// { PROTOTYPE: 'prototype', SPECS: 'specs' }
console.log(require('cloud').ArtifactType);
// Outputs:
// { WEB: 'Web', IOS: 'iOS', ANDROID: 'Android' }
console.log(require('cloud').TargetPlatform);
// Outputs:
// { LINKABLE: 'linkable',
//   PASSWORD_PROTECTED: 'passwordProtected',
//   INVITE_ONLY: 'inviteOnly' }
console.log(require('cloud').AccessLevel);
```

Cool. With that information in hand, we can write the enums as follows:

```ts
export enum ArtifactType {
    PROTOTYPE   = 'prototype',
    SPECS       = 'specs'
}

export enum TargetPlatform  {
    WEB     = 'Web',
    IOS     = 'iOS',
    ANDROID = 'Android'
}

export enum AccessLevel {
    LINKABLE            = 'linkable',
    PASSWORD_PROTECTED  = 'passwordProtected',
    INVITE_ONLY         = 'inviteOnly'
}
```

Once those definitions are added the errors go away!

# Definitions Out-of-Sync, Though...

It should also be noted that the declarations in `cloud.d.ts` appear to be out-of-sync with those in the [current documentation](https://adobexdplatform.com/plugin-docs/reference/cloud.html).

In the current version, the `PrototypeArtifact` and `SpecsArtifact` types are effectively "extensions" of a new `BaseSharedArtifact`. It also appears that there's a documentation bug for the description of the `BaseSharedArtifact.type` member in that it appears to suggest that it is constantly `ArtifactType.PROTOTYPE`. I'd be willing to bet my hat that that is a copy-pasta error.

While [it is possible](https://stackoverflow.com/a/41385149/5285364) to "extend" a `type` declaration, I would _highly_ recommend converting these `types` into `interface`s. Adobe's use of "typedef" in the documentation simply suggests that "this is the shape of an object". You can use a TypeScript `interface` to match that purpose (especially when typedef 'inheritance' is suggested).

Note that if you **_do_** adjust the declarations and unify the two `Artifact` types with the `BaseSharedArtifact`, you could get away _without_ adding the enum values as explained above. It might be better, however, to do something like:

```ts
interface BaseSharedArtifact {
    type: ArtifactType;
    // Other common declarations...
}

interface PrototypeArtifact extends BaseSharedArtifact {
    type: ArtifactType.PROTOTYPE;
    // Prototype-specific declarations...
}

interface SpecsArtifact extends BaseSharedArtifact {
    type: ArtifactType.SPECS;
    // Specs-specific declarations...
}
```

At which point you _would_ still need those enum values.

### PR DESCRIPTION
**Pull request by pklaschka**
- fixes #49
- fixes #52 
- fixes #53 
- fixes #55 

As requested by @ericdrobinson in the issue mentioned above – thanks for your input 👍

### CODE REVIEW

**Comment by pklaschka** [comment]
@ericdrobinson 
> Should indicate the default. Example:
> 
> ```ts
> /**
>  * Optional. Format to read: one of `storage.formats.utf8` or `storage.formats.binary`.
>  * 
>  * Default: `storage.formats.utf8`.
>  */
> format?: typeof formats.utf8 | typeof formats.binary = storage.formats.utf8;
> ```

I actually wanted to do that, but it got marked as a syntax error. Here is a screenshot of the corresponding linting output of the TypeScript playground (https://www.typescriptlang.org/play/):
image



> You don't need to specify the `{object}` type here. A more specific version is actually specified in the API footprint just below it.
> 
> This goes for a few of the `options` definitions in this file.

Noted. I'll fix that tomorrow 😉

**Comment by ericdrobinson** [comment]
>I actually wanted to do that, but it got marked as a syntax error.

I am **_so_** confused as to why this isn't being tagged as a syntax error in VSCode. 😖 Looks like it's time to start running suggestions through the Playground first!

## How about that `@default` tag, though? 😉

The `@default` JSDoc tag doesn't appear to be well supported by TypeScript. Indeed, it does not appear in the [currently best?] [list of supported JSDoc[-style] tags](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) in TypeScript. What's more, it doesn't appear that [TSDoc](https://microsoft.github.io/tsdoc/), a "doc comment [standard](https://github.com/microsoft/tsdoc/) for the TypeScript language", recognizes it. (Try adding it to the default example in that playground.)

I also checked the NodeJS type declarations and they simply state things like "default value is 5" directly...

On another note, [this RFC](https://github.com/microsoft/tsdoc/issues/151) for documenting the default value of a parameter makes for enlightening reading. The default parameter checking appears to work in TypeScript files (*.ts) but **not** type declaration files (*.d.ts). I wonder if VSCode is interpreting `uxp.d.ts` as a pure TypeScript file for some reason...

**Comment by pklaschka** [comment]
Wow – I didn't know `@default` wasn't part of the TSDoc (or whatever it's called) spec. Coming from a JSDoc background, this feels like a "standard" tag to me (cf. https://jsdoc.app/tags-default.html).

It also means that this renders great in WebStorm:
image

Is there some sort of real "spec" (like the JSDoc stuff above) where I can take a look at what's actually supported? The thing is that if there isn't, we simply have to use some subset that fits most platforms (and could argue about every tag that's in JSDoc) 😆...

The thing is that this is kind of a "decision of principle" (if that's something one can say in English). We can either use the smallest subset (which would only include `@param` and `@return`) to hopefully support every platform that has some basic support for those doc comments, or we can use features and some platforms will make something strange out of them.

From what I've seen, also VSCode kind of supports the default tag (in the same way it does the param one):
image

At the same time, VSCode doesn't appear to support the `@link` tag, which is in the specs of both JSDoc and what you can find about TSDoc.

All in all, I think we have to "draw the line" of which things to use somewhere. If this doesn't get interpreted correctly, a developer sees

```
@default some value
```

which should be possible to understand (and therefore fine with me). At the same time, in some editors (like WebStorm), this adds benefits. Therefore, I'd argue that the usage of `@default` – as long as there's no real spec of what can and can't be used – is fine (we don't want to use the TSDoc tool to build the documentation from the typings, after all). This, however, is, of course, open for debate – if we, however, decide to remove the default tags, we'll have to remove others as well (to be consistent) and losing tags like `@link` or `@see` would make the typings less valuable as a tool for development and therefore – in my opinion – defeat the purpose for which I've created them.

Please don't get me wrong here: I'm totally open for doing things like that, but I do believe that it's a decision where there's no right or wrong (based on the reasoning above) and therefore, that this has to be a decision of which direction the typings should take. This, of course, isn't something I'll do based on the suggestion of one person.

**Comment by pklaschka** [comment]
Just to explain why this is kind of a big thing for me:
To change this (due to the reasoning above), we'd have to change the direction the repo should take. Removing a tag like `default´ (again, see my reasoning above) would require sacrificing a guiding principle of me in maintaining the typings. Since this is basically a primary guiding principle for me, I'm not sure that I'd be able to – with a good conscience – maintain the repo any longer (since without being on par with these principles, I wouldn't be able to make confident decisions for the repo any longer).

This wouldn't be a problem for me – this really isn't about ego – but I just want to explain why this is more fundamental to me than just "removing" the `@default` tag (a change of maintenance is – after all – not a small deal) 😉.

**Comment by ericdrobinson** [comment]
>Wow – I didn't know `@default` wasn't part of the TSDoc (or whatever it's called) spec. Coming from a JSDoc background, this feels like a "standard" tag to me.

Honestly, it's been a bit of a crazy ride figuring out which JSDoc tags do and don't work with TypeScript. I used to start by looking at the JSDoc documentation, but quickly found that it lead to broken IntelliSense or frustrating time lost trying to get some JavaScript-side type assertion working.

Annoyingly, [this page](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript) used to have a decent writeup of supported JSDoc tags. It now points to [this page](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) which, right when you need it most, points right back at the first one:

>You can find the full list of supported JSDoc patterns in the [JSDoc support in JavaScript documentation](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript).

Honestly, I think this may all be related to Microsoft's TSDoc efforts - they're probably sick and tired of the ambiguity around which JSDoc tags are supported and exactly _how_ to support them.

That all said, Google did pop up [this page](https://github.com/microsoft/TypeScript-wiki/blob/master/JSDoc-support-in-JavaScript.md) which looks to be very recently maintained. Of note is that the [Unsupported tags](https://github.com/microsoft/TypeScript-wiki/blob/master/JSDoc-support-in-JavaScript.md#unsupported-tags) list at the bottom includes several that are used in tech that will or already purport to conform to TSDoc standards.

>It also means that this renders great in WebStorm

That's pretty sweet! I guess this is one of those situations that is leading MS to push for a standard - so tech developers can provide a consistent experience across tools.

>Is there some sort of real "spec" (like the JSDoc stuff above) where I can take a look at what's actually supported? The thing is that if there isn't, we simply have to use some subset that fits most platforms (and could argue about every tag that's in JSDoc) 😆...

Yup. It's a total PITA. The best list I've found is [this one](https://api-extractor.com/pages/tsdoc/doc_comment_syntax/). [The API Extractor tool (also by MS) is built for generating documentation from TypeScript source files.] There is also [this list](https://www.npmjs.com/package/tsd-jsdoc#unsupported-features) though I'm not sure where the `tsd-jsdoc` folks sourced their supported/unsupported tags lists from. ¯\\_(ツ)\_/¯

>The thing is that this is kind of a "decision of principle" (if that's something one can say in English). We can either use the smallest subset (which would only include `@param` and `@return`) to hopefully support every platform that has some basic support for those doc comments, or we can use features and some platforms will make something strange out of them.

I guess. There's the lists I've just pointed out as well as the fact that MarkDown in the comments seems to be fairly universally supported. This includes code blocks and ordered/unordered lists. I did a test a few days ago to see if I could get one of the "Information warning" blocks into the IntelliSense and it worked fine with a bit of MarkDown spice.

>From what I've seen, also VSCode kind of supports the default tag (in the same way it does the param one)

It does to an extent. I ran a quick test and noticed that typing `@plaschka 5` produced something that also looked reasonably "correct":

image

No idea why `@default` pops the value to a new line... again: ¯\\_(ツ)\_/¯

>At the same time, VSCode doesn't appear to support the `@link` tag, which is in the specs of both JSDoc and what you can find about TSDoc.

Hmm... it may be the case that TSDoc is ahead of the game. The `@link` tag appears in the "Unsupported tags" list that I mentioned before, which points to an [open issue](https://github.com/microsoft/TypeScript-wiki/blob/master/JSDoc-support-in-JavaScript.md#unsupported-tags) about supporting it with TypeScript. So... not yet on that one?

>I do believe that it's a decision where there's no right or wrong

I agree. It's why I specifically "recommended" not using `@default` instead of opening an issue about it. 😀 I brought it up again because there was no response about it in the followups and I wanted to make sure it wasn't missed. The added discussion pieces were there to provide some more context.

>To change this (due to the reasoning above), we'd have to change the direction the repo should take. Removing a tag like `default´ (again, see my reasoning above) would require sacrificing a guiding principle of me in maintaining the typings.

If you feel strongly about it then it seems the answer is "Yup, I considered it but I think `@default` works for now." 😀

In no way do I intend to elbow my way in and demand conformance to an as-yet inflight spec! Apologies if I came off that way. 😔 My intention was merely to raise a concern and provide options. Regardless, thanks for your efforts in maintaining these typings!

**Comment by pklaschka** [comment]
> If you feel strongly about it then it seems the answer is "Yup, I considered it but I think `@default` works for now." 😀
> 
> In no way do I intend to elbow my way in and demand conformance to an as-yet inflight spec! Apologies if I came off that way. 😔 My intention was merely to raise a concern and provide options. Regardless, thanks for your efforts in maintaining these typings!

No apology necessary – I also don't think it came off that way. I just wanted to make it clear how (and – more importantly – why) I feel about his as I do. Thank **you** for bringing this up. As I said, my concern is what the community wants for this, and for the community to voice an opinion, it is important that it gets brought up. At the same time, I think it's important to be transparent about how I think about it (trying to keep the typings as consistent as possible) and "how far" I can go while still being honest (to myself) and therefore able to maintain the repo.

I think that for now, I'll stick with `@default` until there is a more pressing reason (with partial support from both editors, it at least doesn't break anything for now 😉) or there is a huge need for this in the community.

For this Pull Request, however, I think we can agree to leave it the way it is now. I'll probably create an issue (+ a label for "to be discussed") tomorrow to see how everyone else thinks about it and have a place for searching for an optimal (if there is one) solution for everyone, but for now, I'll call it a day 🙂

**Comment by pklaschka** [comment]
> Just to explain why this is kind of a big thing for me:
> To change this (due to the reasoning above), we'd have to change the direction the repo should take. Removing a tag like `default´ (again, see my reasoning above) would require sacrificing a guiding principle of me in maintaining the typings. Since this is basically a primary guiding principle for me, I'm not sure that I'd be able to – with a good conscience – maintain the repo any longer (since without being on par with these principles, I wouldn't be able to make confident decisions for the repo).
> 
> This wouldn't be a problem for me – this really isn't about ego – but I just want to explain why this is more fundamental to me than just "removing" the `@default` tag (a change of maintenance is – after all – not a small deal) 😉.
> 
> Edit: On the second read, this sounds much more "emotional" and "extreme" than it was intended to be.
> I only mean to say that changing this would "start" a trend into another direction for this repo. Of course, removing the `@default`s wouldn't lead to me being unable to maintain the repo any longer. It would, however, mean that the repository's moving into a direction where I can't see a guiding thread. Since I wouldn't want to hold the repository back by "not seeing through it" in such a case, I'd search for a maintainer who's best-suited for that direction. So don't get me wrong: This isn't about `@default`, but just about a general direction this stands for in which I wouldn't feel like the maintainer this repository deserves anymore (since I couldn't honestly say I'm 100% confident in my decisions, in such a case).

To just make it a bit more transparent (and kind of a TL;DR version) what's the issue for me here 🙂 :
What this comes down to is a question of the spec vs. searching for the most practical solution (may this be in the spec or not). Whenever I decide how to do something in the typings, I try to optimize for the practical side of it (as good as I can) since I believe that it is a tool making our lifes as devs easier and it is, therefore, less important for it to follow all guidelines and specs and more important to work as ideal as possible in as many scenarios as possible. All in all, this therefore really isn't about the specific issue discussed here, but more about this "way" I always use when doing the typings. It is this way that allows me to be confident about the decisions I make. Since I've created the repo I'm passionate about it and if it gets decided that we wish to divert from that way, that's perfectly fine with me. It's just that in that case, I couldn't be as confident in my decisions anymore and wouldn't want to hold the repo back because of that.

**Comment by ericdrobinson** [comment]
>I think that for now, I'll stick with `@default` until there is a more pressing reason (with partial support from both editors, it at least doesn't break anything for now 😉) or there is a huge need for this in the community.

Sounds great to me!

---

>For this Pull Request, however, I think we can agree to leave it the way it is now. I'll probably create an issue (+ a label for "to be discussed") tomorrow to see how everyone else thinks about it and have a place for searching for an optimal (if there is one) solution for everyone

Awesome. That would be great. As mentioned in [this comment](https://github.com/AdobeXD/typings/issues/49#issuecomment-506409333), it **_looks_** like the TypeScript-recognized list of JSDoc tags is [here](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc). That "looks" is emphasized because the explanation seems to suggest that it's context-sensitive (emphasis mine):

>currently supported when using JSDoc annotations to provide type information **in JavaScript files**.

What we haven't clearly stated yet is the _context_ for the JSDoc tags we've been discussing: JavaScript or TypeScript? It appears that in a **TypeScript context**, JSDoc tags may simply be "comment text". Consider the following code in a TypeScript context:

```ts
/** @type {number} */
let test = "hey";
```

The code snippet above does not produce an error in a TypeScript file. It **_does_** produce an error in a JavaScript file [in VSCode], though!

What this all suggests to me right now is that JSDoc is **not** a thing that the _**TypeScript**_ language (read: the language server) actually cares about. Indeed, upon closer inspection, it appears that [VSCode interprets the JSDocs](https://code.visualstudio.com/docs/languages/typescript#_jsdoc-support) in the comments itself when performing certain helpful actions (the standard IntelliSense feautres)!

And this is where [TSDoc](https://github.com/microsoft/tsdoc#why-do-we-need-tsdoc) comes in:

>Many... tools in today's web developer community want to interact with TypeScript doc comments. Each of these tools accepts a syntax that is loosely based on [JSDoc](http://usejsdoc.org/), but encounters frustrating incompatibilities when attempting to coexist with other parsers.

It seems that TSDoc may _eventually_ present us with a standardized set of tags to use for consistent tooling, but we're not there yet. **As such, I think opening a "future discussions" issue to track developments around TSDoc is a great idea.**

_[Side note: TSDoc has an RFC for an [`@defaultValue`](https://github.com/Microsoft/tsdoc/issues/27) tag 😉]_

---

>For this Pull Request, however, I think we can agree to leave it the way it is now.

Yes. Please do!

---

**Comment by pklaschka** [comment]
Ok. With that, we should be ready to merge this. I'll wait until the end of today and if there are no vetos, I'll merge it. I'll also open the issue for future discussions regarding this later today (I didn't get to doing so yesterday since I had to take my cat to the vet – no worries, she'll be fine – but I'll do it later today).

**Comment by pklaschka** [comment]
- Fixes #53

**Comment by pklaschka** [comment]
Discussion about `@default` and doc comments, in general, should be continued in #58

**Pull request merged**
