### PR TITLE
npm typings support

### PR DESCRIPTION
**Pull request by tato123**
## Changes
- Update the project to include a package.json

## Testing
- Verified in the [XD-Template-Project](https://github.com/tato123/xd-template-project)

## Additional Notes
In order for individuals to pull this down outside of the definitelytyped project a contributor or owner will need to publish this project to NPM

### CODE REVIEW

**Comment by tato123** [comment]
Thanks, I wasn't sure how to go about getting that information, so that's a really great callout 👍

**Comment by pklaschka** [comment]
fixes #28

**Comment by pklaschka** [comment]
A side-note:

Another thing that might be useful is if someone (whoever that may be, I – unfortunately – would only get to do so in about two weeks) could update the Wiki to include instructions on how to use it for developing with Typescript once it is pushed.

**Comment by pklaschka** [comment]
@kerrishotts Do you have any thoughts on how we could efficiently publish this to npm (may I ask how the workflow works with xdpm?)? Thank you very much in advance...

**Comment by pklaschka** [comment]
Alright – I'll just go ahead and merge this now, and we'll worry about how to get this onto npm after that 😉

**Comment by pklaschka** [comment]
@tato123 Congratulations to your first contribution to the typings repo 🎉 😉

**Comment by mattThousand** [comment]
@tato123 sorry to bug you with a simple request - I am a swift developer having trouble getting up and running in `Typescript` land. Any chance you could add "getting started" instructions to the wiki?

**Comment by mattThousand** [comment]
@tato123 @pklaschka which Typescript version are you using? I think this may be the reason I'm not able to compile on my end... I am using `3.2.1` 🤔

**Comment by tato123** [comment]
@mattThousand I'm using the same version however I was not using `tsc`, I was using babel-7 typescript preset and a tsconfig to mainly typecheck my files in vscode. 

@mattThousand are you compiling with `tsc`? 

Since I don't compile with tsc it doesn't care about the typings however I want to make sure this works for you, do you have sample code youd mind sharing?

**Comment by mattThousand** [comment]
thanks for getting back to me @tato123 - yes, I am trying to compile using `tsc` but getting a whole heap of compilation errors... here is the bare-bones project I am using: https://github.com/mattThousand/typings

**Comment by mattThousand** [comment]
let me know if I'm missing something obvious 😄 . Would not be surprised if I am going about things entirely incorrectly (I am new to this stack)

**Comment by pklaschka** [comment]
@mattThousand Since I'm not an expert in getting tsc to work with it either, this is just an attempt: Could you maybe try if it works when you use this `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "baseUrl": ".",
    "paths": {
      "scenegraph": ["./node_modules/@adobexd/typings/types/scenegraph"],
      "application": ["./node_modules/@adobexd/typings/types/application"],
      "commands": ["./node_modules/@adobexd/typings/types/commands"],
      "uxp": ["./node_modules/@adobexd/typings/types/uxp"],
      "os": ["./node_modules/@adobexd/typings/types/os"]
    },

    "typeRoots": ["@types","./node_modules/@adobexd/"],
    "outDir": "./built"
  },
  "include": [
      "./src/**/*"
  ]
}
```

It at least works for me – let me know if it does for you as well.

**Comment by mattThousand** [comment]
@pklaschka @tato123 not explicitly including the `node_modules` directory did the trick for me. I am baffled, but thankfully in a place where I can start being productive with your marvelous types 😄

Sorry to bug you!

**Comment by pklaschka** [comment]
@mattThousand Whatever works 😉 

No need to say sorry – all such things help to create better docs for this (learning what are challenges and how they can get resolved in individual cases), so it's really something good for both sides.

I'm happy you've found a solution and if you have any further issues or find any other (unexpected) solutions, feel free to open an issue.

**Pull request merged**
